version: '2'
services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "7199:7199"

    environment:
      JVM_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=cassandra1 -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=1098"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  controller:
    image: dtr.corp.appdynamics.com/appdynamics/enterprise-console:4.5.12.20345
    container_name: controller
    ports:
      - "8080:8080"
      - "9080:9080"
      - "9200:9200"

  machine:
    container_name: machine
    environment:
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=customer1
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=SJ5b2m7d1$$354
      - APPDYNAMICS_CONTROLLER_HOST_NAME=controller
      - APPDYNAMICS_CONTROLLER_SSL_ENABLED=false
      - APPDYNAMICS_CONTROLLER_PORT=8080
      - EVENTS_SERVICE_HOST=controller
      - MACHINE_AGENT_PROPERTIES=-Dappdynamics.agent.uniqueHostId=cassandraTest -Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=false
      - CASSANDRA_HOST_1=cassandra1
      - CASSANDRA_PORT_1=7199
      - CASSANDRA_USERNAME_1=cassandra
      - CASSANDRA_PASSWORD_1=cassandra
    build:
      context: .
      dockerfile: Dockerfile_MA

    volumes:
      - /:/hostroot:ro
      - /var/run/docker.sock:/var/run/docker.sock

  workbench:
    environment:
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=customer1
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=SJ5b2m7d1$$354
      - APPDYNAMICS_CONTROLLER_HOST_NAME=controller
      - APPDYNAMICS_CONTROLLER_SSL_ENABLED=false
      - APPDYNAMICS_CONTROLLER_PORT=8080
      - EVENTS_SERVICE_HOST=controller
      - MACHINE_AGENT_PROPERTIES=-Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=false
      - CASSANDRA_HOST_1=localhost
      - CASSANDRA_PORT_1=7199

    build:
      context: .
      dockerfile: Dockerfile_Workbench
      args:
        - ENCRYPTION_KEY=${ENCRYPTION_KEY}
        - PLAINTEXT_PWD=${PLAINTEXT_PWD}

    ports:
      - "9089:9089"

    volumes:
      - /:/hostroot:ro
      - /var/run/docker.sock:/var/run/docker.sock