# List of cassandra servers
servers:
  - host: "localhost"
    port: 7199
    username: ""
    password: ""
    displayName: "localhost"


# number of concurrent tasks
numberOfThreads: 10

#timeout for the thread
threadTimeout: 30

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|Cassandra|"

#Metric Overrides. Change this if you want to transform the metric key or value or its properties.
metricOverides:
  - metricKey: ".*Ratio.*"
    postfix: "Percent"
    multiplier: 100

  - metricKey: ".*Cache.*Rate.*"
    postfix: "Percent"
    multiplier: 100
