# List of cassandra servers
servers:
  - host: "localhost"
    port: 7199
    username: ""
    password: ""
    displayName: "localhost"


# cassandra mbeans. Exclude patterns with regex can be used to exclude any unwanted metrics.
mbeans:
  - domainName: "org.apache.cassandra.metrics"
    excludePatterns: [
    ]

# number of concurrent tasks
numberOfThreads: 10

#timeout for the thread
threadTimeout: 30

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|Cassandra|"

#Metric Overrides. Change this if you want to transform the metric key or value or its properties.
metricOverides:
  - metricKey: "Cache|KeyCache|Hits|MeanRate"
    disabled: false
    postfix: "Percent"
    multiplier: 100
    aggregator : ""
    timeRollup : ""
    clusterRollup : ""

  - metricKey: "ColumnFamilies|.*"
    disabled: true
    multiplier: 100
    aggregator : ""
    timeRollup : ""
    clusterRollup : ""
    postfix: "Percent"

